[[language]]
name = "python"
language-servers = ["basedpyright", "ruff"]
auto-format = true
formatter = { command = "ruff", args = ["format", "--stdin-filename", "main.py"] }

[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]

[language-server.ruff]
command = "ruff"
args = ["server"]
